-dontwarn java.lang.invoke.*
-dontwarn com.rengwuxian.**
-keep class butterknife.*
-keepclasseswithmembernames class * { @butterknife.* <methods>; }
-keepclasseswithmembernames class * { @butterknife.* <fields>; }